export const BATTLE_STATUS = {
  OPEN: 'OPEN',
  JOINED: 'JOINED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESULT_SUBMITTED: 'RESULT_SUBMITTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
} as const;

export const TRANSACTION_TYPES = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  BATTLE_ENTRY: 'BATTLE_ENTRY',
  BATTLE_WIN: 'BATTLE_WIN',
  BATTLE_REFUND: 'BATTLE_REFUND',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  ADMIN_CREDIT: 'ADMIN_CREDIT',
  ADMIN_DEBIT: 'ADMIN_DEBIT',
} as const;

export const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPPORT: 'SUPPORT',
} as const;
